#!/usr/bin/env bash
set -euo pipefail

# Resolve repo path (script lives in repo/scripts)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [[ ! -f "${REPO_DIR}/package.json" ]]; then
  echo "Error: package.json not found. Run this script from the repo or keep it inside the repo." >&2
  exit 1
fi

# Require non-root; use sudo for privileged actions
if [[ "$(id -u)" -eq 0 ]]; then
  echo "Please run as a normal user with sudo privileges, not root." >&2
  exit 1
fi

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

prompt() {
  local label="$1"
  local default="$2"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "${label} [${default}]: " value
    echo "${value:-$default}"
  else
    read -r -p "${label}: " value
    echo "${value}"
  fi
}

prompt_yes_no() {
  local label="$1"
  local default="$2"
  local value
  local hint="y/N"
  if [[ "$default" == "y" ]]; then
    hint="Y/n"
  fi
  read -r -p "${label} (${hint}): " value
  value="${value:-$default}"
  case "$value" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

say() {
  echo "==> $1"
}

say "Tapdance server installer (Ubuntu)"

INSTALL_DIR="$(prompt "Install directory (repo path)" "${REPO_DIR}")"
if [[ ! -d "$INSTALL_DIR" ]]; then
  echo "Directory does not exist: ${INSTALL_DIR}" >&2
  exit 1
fi

cd "$INSTALL_DIR"

# Ensure basic tools
if ! need_cmd git; then
  say "Installing git"
  sudo apt-get update -y
  sudo apt-get install -y git
fi

if ! need_cmd curl; then
  say "Installing curl"
  sudo apt-get update -y
  sudo apt-get install -y curl
fi

NODE_OK=false
NODE_VERSION=""
if need_cmd node; then
  NODE_VERSION="$(node -v | sed 's/^v//')"
  NODE_MAJOR="${NODE_VERSION%%.*}"
  if [[ "$NODE_MAJOR" -ge 22 ]]; then
    NODE_OK=true
  fi
fi

# Install Node.js if missing or too old
if ! $NODE_OK; then
  echo "Node.js 22+ is recommended. Current: ${NODE_VERSION:-not installed}"
  echo "Choose Node.js install method:"
  echo "  1) NodeSource (installs Node 22)"
  echo "  2) Ubuntu apt (may be older)"
  echo "  3) Skip"
  read -r -p "Select [1/2/3]: " node_choice
  case "$node_choice" in
    1)
      say "Installing Node.js 22 via NodeSource"
      curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
      sudo apt-get install -y nodejs
      ;;
    2)
      say "Installing Node.js via apt"
      sudo apt-get update -y
      sudo apt-get install -y nodejs npm
      ;;
    3)
      echo "Skipping Node.js install. You must install Node 22+ manually."
      ;;
    *)
      echo "Invalid choice. Exiting." >&2
      exit 1
      ;;
  esac
fi

# Ensure npm is present
if ! need_cmd npm; then
  say "npm not found. Installing via apt"
  sudo apt-get update -y
  sudo apt-get install -y npm
fi

# Install frontend deps
say "Installing dependencies"
npm install

# Build static frontend
say "Build frontend"
VITE_BRIDGE_URL="/api/seedance"

ENV_FILE="${INSTALL_DIR}/.env"
# Prepare .env with bridge base URL and optional keys
if [[ -f "$ENV_FILE" ]]; then
  if prompt_yes_no "Found existing .env. Back up to .env.bak and recreate?" "n"; then
    cp "$ENV_FILE" "${ENV_FILE}.bak"
    rm -f "$ENV_FILE"
  fi
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "# Generated by install_server.sh" > "$ENV_FILE"
  echo "VITE_SEEDANCE_BRIDGE_URL=${VITE_BRIDGE_URL}" >> "$ENV_FILE"
  echo "" >> "$ENV_FILE"
fi

if prompt_yes_no "Configure Gemini API key now?" "n"; then
  GEMINI_KEY="$(prompt "GEMINI_API_KEY" "")"
  if [[ -n "$GEMINI_KEY" ]]; then
    echo "GEMINI_API_KEY=\"${GEMINI_KEY}\"" >> "$ENV_FILE"
  fi
fi

if prompt_yes_no "Configure Volcengine Ark API key now?" "n"; then
  ARK_KEY="$(prompt "ARK_API_KEY" "")"
  if [[ -n "$ARK_KEY" ]]; then
    echo "ARK_API_KEY=\"${ARK_KEY}\"" >> "$ENV_FILE"
  fi
fi

if prompt_yes_no "Configure Volcengine TOS access keys now?" "n"; then
  TOS_AK="$(prompt "TOS_ACCESS_KEY" "")"
  TOS_SK="$(prompt "TOS_SECRET_KEY" "")"
  if [[ -n "$TOS_AK" ]]; then
    echo "TOS_ACCESS_KEY=\"${TOS_AK}\"" >> "$ENV_FILE"
  fi
  if [[ -n "$TOS_SK" ]]; then
    echo "TOS_SECRET_KEY=\"${TOS_SK}\"" >> "$ENV_FILE"
  fi
fi

# Build assets (uses .env)
say "Running build"
npm run build

# Install Dreamina CLI
say "Installing Dreamina CLI"
echo "The CLI installer will run: curl -fsSL https://jimeng.jianying.com/cli | bash"
if prompt_yes_no "Run CLI installer now?" "y"; then
  curl -fsSL https://jimeng.jianying.com/cli | bash
else
  echo "Skipping CLI install. You must install it manually before using Seedance CLI features."
fi

# Create and start systemd service for bridge
say "Setting up Seedance bridge service"
NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]]; then
  echo "Error: node not found in PATH. Cannot create service." >&2
  exit 1
fi

SERVICE_NAME="tapdance-seedance-bridge"
SERVICE_PATH="/etc/systemd/system/${SERVICE_NAME}.service"

sudo tee "$SERVICE_PATH" >/dev/null <<EOF
[Unit]
Description=Tapdance Seedance Bridge
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=${NODE_BIN} ${INSTALL_DIR}/server/seedanceBridge.mjs
Restart=on-failure
Environment=SEEDANCE_BRIDGE_PORT=3210
Environment=RENREN_APP_DATA_DIR=${INSTALL_DIR}/local_data

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"

# Choose web server (Caddy or Nginx)
say "Choose web server"
echo "  1) Caddy (recommended, supports self-signed HTTPS)"
echo "  2) Nginx (HTTP only by default)"
read -r -p "Select [1/2]: " web_choice

WEB_DOMAIN="$(prompt "Domain or IP" "localhost")"
ENABLE_HTTPS=false
if [[ "$web_choice" == "1" ]]; then
  if ! need_cmd caddy; then
    say "Installing Caddy"
    sudo apt-get update -y
    sudo apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    sudo apt-get update -y
    sudo apt-get install -y caddy
  fi

  if prompt_yes_no "Enable HTTPS with self-signed cert (Caddy internal CA)?" "y"; then
    ENABLE_HTTPS=true
  fi

  CADDYFILE="/etc/caddy/Caddyfile"
  if $ENABLE_HTTPS; then
    sudo tee "$CADDYFILE" >/dev/null <<EOF
${WEB_DOMAIN} {
  root * ${INSTALL_DIR}/dist
  file_server

  handle_path /api/seedance/* {
    reverse_proxy 127.0.0.1:3210
  }

  tls internal
}
EOF
  else
    sudo tee "$CADDYFILE" >/dev/null <<EOF
http://${WEB_DOMAIN} {
  root * ${INSTALL_DIR}/dist
  file_server

  handle_path /api/seedance/* {
    reverse_proxy 127.0.0.1:3210
  }
}
EOF
  fi

  sudo systemctl enable caddy
  sudo systemctl restart caddy

elif [[ "$web_choice" == "2" ]]; then
  if ! need_cmd nginx; then
    say "Installing Nginx"
    sudo apt-get update -y
    sudo apt-get install -y nginx
  fi

  NGINX_SITE="/etc/nginx/sites-available/tapdance"
  sudo tee "$NGINX_SITE" >/dev/null <<EOF
server {
  listen 80;
  server_name ${WEB_DOMAIN};

  root ${INSTALL_DIR}/dist;
  index index.html;

  location / {
    try_files \$uri /index.html;
  }

  location /api/seedance/ {
    proxy_pass http://127.0.0.1:3210/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
  }
}
EOF

  sudo ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/tapdance
  sudo rm -f /etc/nginx/sites-enabled/default
  sudo systemctl enable nginx
  sudo systemctl restart nginx

else
  echo "Invalid web server choice. Exiting." >&2
  exit 1
fi

say "Done"
if [[ "$web_choice" == "1" && "$ENABLE_HTTPS" == "true" ]]; then
  echo "Access via: https://${WEB_DOMAIN}"
  echo "Note: This uses a self-signed certificate (Caddy internal CA)."
else
  echo "Access via: http://${WEB_DOMAIN}"
fi

cat <<'EOF'

Next steps:
1) If using Seedance CLI, ensure you are logged in:
   dreamina login
2) Check bridge status:
   systemctl status tapdance-seedance-bridge
3) Check web server status:
   systemctl status caddy || systemctl status nginx
EOF
